
% Matlab script stereonet.m
% To plot lines and planes in stereographic
% (equal-angle) projections
clf

% Read input data on planes
%load planes.dat

% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/bjung/github/dfnWorks/hlwd-2021/data/Az_dip_KSRS_csv.csv
%
% Auto-generated by MATLAB on 06-Apr-2021 14:14:59

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Depth_m", "Azimuth_deg", "Dip_deg"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
AzdipKSRScsv = readtable("/home/bjung/github/dfnWorks/hlwd-2021/data/Az_dip_KSRS_csv.csv", opts);

% Clear temporary variables
clear opts


% assign variables
planes=  table2array(AzdipKSRScsv(:,2:3));


% Original code for stereonet plotting

% Data in column 1 are strikes, and data in column 2 are dips
% of planes, with angles given in degrees
strike = planes(:,1)*pi/180;
dip = planes(:,2)*pi/180;
num = length(strike);

Stereonet(0,90*pi/180,10*pi/180,1)

