% Matlab script stereonet.m
% To plot lines and planes in stereographic
% (equal-angle) projections
clf

% Read input data on planes
%load planes.dat

% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/bjung/github/dfnWorks/hlwd-2021/data/Az_dip_KSRS_csv.csv
%
% Auto-generated by MATLAB on 06-Apr-2021 14:14:59

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Depth_m", "Azimuth_deg", "Dip_deg"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
AzdipKSRScsv = readtable("/home/bjung/github/dfnWorks/hlwd-2021/data/Az_dip_KSRS_csv.csv", opts);

% Clear temporary variables
clear opts


% assign variables
planes=  table2array(AzdipKSRScsv(:,2:3));


% Original code for stereonet plotting

% Data in column 1 are strikes, and data in column 2 are dips
% of planes, with angles given in degrees
strike = planes(:,1)*pi/180;
dip = planes(:,2)*pi/180;
num = length(strike);


% Calculate poles from strikes/dips

for i=1:num
    [pstrike(i),pdip(i)] = Pole(strike(i),dip(i),1);
end







% % find cyclographic traces of planes and plot them
% R = 1;
% rake = 0:pi/180:pi;
% for i=1:num
%     plunge = asin(sin(dip(i)).*sin(rake));
%     trend = strike(i) + atan2(cos(dip(i)).*sin(rake), cos(rake));
%     rho = R.*tan(pi/4 - (plunge/2));
%     % polarb plots ccl from 3:00, so convert to cl from 12:00
%     polarplot(pi/2-trend,rho,'-')
%     hold on
% end
% 
% 

% another source code able to plot geological applications
figure
Stereonet(0,pi/2,10*pi/180,1)
%Stereonet(trdv,plgv,intrad,sttype)
%Stereonet plots an equal angle or equal area stereonet of unit radius
%in any view direction
%
%   USE: Stereonet(trdv,plgv,intrad,stttype)
%
%   trdv = trend of view direction
%   plgv = plunge of view direction
%   intrad = interval in radians between great or small circles 
%   sttype = An integer indicating the type of stereonet. 0 for equal angle,
%            and 1 for equal area
%
%   NOTE: All angles should be entered in radians
%
%   Example: To plot an equal area stereonet at 10 deg intervals in a
%   default view direction type:
%
%   Stereonet(0,90*pi/180,10*pi/180,1);
%
%   To plot the same stereonet but with a view direction of say: 235/42,
%   type:
%
%   Stereonet(235*pi/180,42*pi/180,10*pi/180,1);
%
%   Stereonet uses functions Pole, GeogrToView, SmallCircle and GreatCircle
%
%MATLAB script written by Nestor Cardozo for the book Structural 
%Geology Algorithms by Allmendinger, Cardozo, & Fisher, 2011. If you use
%this script, please cite this as "Cardozo in Allmendinger et al. (2011)"


%scatter(pstrike,pdip,'k'); % plot reference circle
